apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: rest-producer
  name: rest-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rest-producer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: rest-producer
    spec:
      containers:
        - image: lombardo/kafka-rest-producer:latest
          name: rest-producer
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
